name: Build Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deb:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up dependencies
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts lintian

      # 3) Generate version number using GITHUB_RUN_NUMBER
      - name: Increment version number
        id: version
        run: |
          # Read the base version from changelog (if present) or default to 1.0.0
          if [ -f "debian/changelog" ]; then
            BASE_VERSION=$(dpkg-parsechangelog --show-field Version | cut -d'-' -f1)
          else
            BASE_VERSION="1.0.0"
          fi

          # Split the base version into MAJOR and MINOR (ignore patch)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$BASE_VERSION"

          # Incorporate the GitHub Actions run number as the new patch version
          NEW_VERSION="${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"

          # Update the changelog with the new version
          export DEBFULLNAME="GitHub Actions"
          export DEBEMAIL="actions@github.com"
          dch --force-distribution -v "$NEW_VERSION" -D "unstable" "Automated build of version $NEW_VERSION"

          # Output the new version number for later steps
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      # 4) Build the package
      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc -b -d
          mkdir -p build
          mv ../*.deb build/

      # 5) Upload artifact
      - name: Upload Debian package
        uses: actions/upload-artifact@v3
        with:
          name: wlanpi-usb-ethernet_${{ env.new_version }}
          path: build/*.deb
